language: node_js
node_js:
  - node 
env:
  global:
    - CC_TEST_REPORTER_ID=b3d6774123481fc320a8564ba195d9482c9bfe7e0676931108dfa69464ee6a6e
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - make lint
  - make test-coverage
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT 
notifications:
  email: false
